#!/usr/bin/env bash
# same as task 0 but -f added to ln to forcefully remove the file if it exists
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
kill "$(pgrep 'nginx' | head -1)"
